require "duplicatable"
require "with_options"

CHECKPOINT_LEVEL = 0
CHECKPOINT_WORLD_GATE = 1
CHECKPOINT_BONUS_LEVEL = 2
CHECKPOINT_GAME_START_POS = 3
CHECKPOINT_WORLD_BEGIN = 4
CHECKPOINT_WORLD_END = 5
